import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { InnerWrap, Wrapper } from "@/lib/atoms";

type Props = {};

export function InvestmentSpecifics() {
  const specifics = [
    {
      title: "Returns",
      details: [
        {
          label: "Principle protection",
          description: "Ensures the original investment amount is safeguarded.",
          value: "Full",
          icon: "",
        },
        {
          label: "Guaranteed annual net yield",
          description: "A guaranteed 8% return on investment per annum.",
          value: "8%",
          icon: "",
        },
        {
          label: "Carried Interest",
          description:
            "Your share of cashflows generated AFTER guaranteed interest is paid.",
          value: "80%",
          icon: "",
        },
        {
          label: "Target annual net yield",
          description:
            "Based on the cashflows generated by assets under management",
          value: "9.3-13%",
          icon: "",
        },
      ],
    },
    {
      title: "Fees",
      details: [
        {
          label: "Entry Fee",
          description: "No subscription fee.",
          value: "None",
          icon: "",
        },
        {
          label: "Annual Management Fee",
          description: "Taken by HelmShare for assets under management.",
          value: "1.21%",
          icon: "",
        },
        {
          label: "Carried Interest",
          description:
            "Taken by HelmShare for cashflows generated AFTER the 8% guarantee is paid.",
          value: "20%",
          icon: "",
        },
        {
          label: "Exit Fee",
          description: "No fees when exiting the fund.",
          value: "None",
          icon: "",
        },
      ],
    },
    {
      title: "Schedule",
      details: [
        {
          label: "Payment schedule",
          description:
            "Get paid every quarter or defer payments as you prefer.",
          value: "Quarterly",
          icon: "",
        },
        {
          label: "Fund Term",
          description: "Total timeline of the fund.",
          value: "6 years",
          icon: "",
        },
      ],
    },
    {
      title: "Structure",
      details: [
        {
          label: "Fund type",
          description: "SPV will be wound-up after 6 years.",
          value: "Closed-ended",
          icon: "",
        },
        {
          label: "Estimated Fund Size",
          description: "Total projected fund capitalization.",
          value: "$ 5M",
          icon: "",
        },
        {
          label: "Offering Structure",
          description: "Special Purpose Vehicle based in the Caymans.",
          value: "SPV",
          icon: "",
        },
        {
          label: "Annual Flat Fee",
          description: "No additional fees",
          value: "None",
          icon: "",
        },
      ],
    },
  ];
  return (
    <Wrapper className="hidden py-8 border-t bg-slate-100 border-slate-200 lg:flex">
      <InnerWrap>
        <div className="flex flex-col items-center justify-center my-12 text-center">
          <p className="uppercase text-[11px] tracking-[0.2em] font-medium text-brand-p1">
            fund details
          </p>
          <h1 className="my-3 text-5xl font-medium tracking-tight font-title">
            Investment Specifics
          </h1>
          <h4 className="mt-4 text-center max-w-prose">
            Our fund offers a unique opportunity to invest in a diversified
            fleet of charter yachts, with a focus on the lucrative and growing
            Seychelles market. Our investment strategy is designed to provide a
            secure, stable-yield income stream over a 6 year term.
          </h4>
        </div>
        <ul className="grid w-full grid-cols-2 gap-4 mt-1 md:grid-cols-4">
          {specifics.map((item, index) => (
            <li
              key={index}
              className="flex flex-col items-start justify-start w-full bg-white border rounded-lg shadow-sm border-zinc-300"
            >
              <p className="text-[10px] uppercase font-semibold tracking-[0.1em] text-slate-600 px-4 py-2">
                {item.title}
              </p>
              <Separator />
              <ul className="flex flex-col w-full py-3">
                {item.details.map((detail, index) => (
                  <li
                    key={index}
                    className="flex flex-col items-center justify-between w-full text-left md:flex-row"
                  >
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger className="flex justify-between w-full px-3 py-1 mx-2 mt-1 text-sm rounded-sm cursor-pointer item-center hover:bg-slate-100">
                          <p> {detail.label}</p>
                          <p className="text-sm font-normal text-green-700">
                            {detail.value}
                          </p>
                        </TooltipTrigger>
                        <TooltipContent>{detail.description}</TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                  </li>
                ))}
              </ul>
            </li>
          ))}
        </ul>
        <div className="flex flex-col items-center justify-center mt-8">
          <h4 className="text-xs">Reasons to invest:</h4>
          <ul className="flex items-center justify-center gap-2 my-2 ">
            <li>
              <Badge variant="outline">Income Guarantee</Badge>
            </li>
            <li>
              <Badge variant="outline">Quarterly Payouts</Badge>
            </li>
            <li>
              <Badge variant="outline">Low Risk</Badge>
            </li>
            <li>
              <Badge variant="outline">Performance Bonus</Badge>
            </li>
            <li>
              <Badge variant="outline">Downside Protection</Badge>
            </li>
          </ul>
          <p className="text-xs text-gray-400">
            *Please refer to the offering memorandum for full details.
          </p>
        </div>
      </InnerWrap>
    </Wrapper>
  );
}
